// Code generated by MockGen. DO NOT EDIT.
// Source: ./paginator/iface.go

// Package mock_paginator is a generated GoMock package.
package mock_paginator

import (
	context "context"
	sql "database/sql"
	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
	reflect "reflect"
	time "time"
)

// MockDBIface is a mock of DBIface interface
type MockDBIface struct {
	ctrl     *gomock.Controller
	recorder *MockDBIfaceMockRecorder
}

// MockDBIfaceMockRecorder is the mock recorder for MockDBIface
type MockDBIfaceMockRecorder struct {
	mock *MockDBIface
}

// NewMockDBIface creates a new mock instance
func NewMockDBIface(ctrl *gomock.Controller) *MockDBIface {
	mock := &MockDBIface{ctrl: ctrl}
	mock.recorder = &MockDBIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDBIface) EXPECT() *MockDBIfaceMockRecorder {
	return m.recorder
}

// New mocks base method
func (m *MockDBIface) New() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// New indicates an expected call of New
func (mr *MockDBIfaceMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockDBIface)(nil).New))
}

// Close mocks base method
func (m *MockDBIface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockDBIfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDBIface)(nil).Close))
}

// DB mocks base method
func (m *MockDBIface) DB() *sql.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*sql.DB)
	return ret0
}

// DB indicates an expected call of DB
func (mr *MockDBIfaceMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockDBIface)(nil).DB))
}

// CommonDB mocks base method
func (m *MockDBIface) CommonDB() gorm.SQLCommon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommonDB")
	ret0, _ := ret[0].(gorm.SQLCommon)
	return ret0
}

// CommonDB indicates an expected call of CommonDB
func (mr *MockDBIfaceMockRecorder) CommonDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommonDB", reflect.TypeOf((*MockDBIface)(nil).CommonDB))
}

// Dialect mocks base method
func (m *MockDBIface) Dialect() gorm.Dialect {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dialect")
	ret0, _ := ret[0].(gorm.Dialect)
	return ret0
}

// Dialect indicates an expected call of Dialect
func (mr *MockDBIfaceMockRecorder) Dialect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dialect", reflect.TypeOf((*MockDBIface)(nil).Dialect))
}

// Callback mocks base method
func (m *MockDBIface) Callback() *gorm.Callback {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Callback")
	ret0, _ := ret[0].(*gorm.Callback)
	return ret0
}

// Callback indicates an expected call of Callback
func (mr *MockDBIfaceMockRecorder) Callback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Callback", reflect.TypeOf((*MockDBIface)(nil).Callback))
}

// LogMode mocks base method
func (m *MockDBIface) LogMode(enable bool) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogMode", enable)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// LogMode indicates an expected call of LogMode
func (mr *MockDBIfaceMockRecorder) LogMode(enable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogMode", reflect.TypeOf((*MockDBIface)(nil).LogMode), enable)
}

// SetNowFuncOverride mocks base method
func (m *MockDBIface) SetNowFuncOverride(nowFuncOverride func() time.Time) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNowFuncOverride", nowFuncOverride)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// SetNowFuncOverride indicates an expected call of SetNowFuncOverride
func (mr *MockDBIfaceMockRecorder) SetNowFuncOverride(nowFuncOverride interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNowFuncOverride", reflect.TypeOf((*MockDBIface)(nil).SetNowFuncOverride), nowFuncOverride)
}

// BlockGlobalUpdate mocks base method
func (m *MockDBIface) BlockGlobalUpdate(enable bool) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockGlobalUpdate", enable)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// BlockGlobalUpdate indicates an expected call of BlockGlobalUpdate
func (mr *MockDBIfaceMockRecorder) BlockGlobalUpdate(enable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockGlobalUpdate", reflect.TypeOf((*MockDBIface)(nil).BlockGlobalUpdate), enable)
}

// HasBlockGlobalUpdate mocks base method
func (m *MockDBIface) HasBlockGlobalUpdate() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasBlockGlobalUpdate")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasBlockGlobalUpdate indicates an expected call of HasBlockGlobalUpdate
func (mr *MockDBIfaceMockRecorder) HasBlockGlobalUpdate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasBlockGlobalUpdate", reflect.TypeOf((*MockDBIface)(nil).HasBlockGlobalUpdate))
}

// SingularTable mocks base method
func (m *MockDBIface) SingularTable(enable bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SingularTable", enable)
}

// SingularTable indicates an expected call of SingularTable
func (mr *MockDBIfaceMockRecorder) SingularTable(enable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SingularTable", reflect.TypeOf((*MockDBIface)(nil).SingularTable), enable)
}

// NewScope mocks base method
func (m *MockDBIface) NewScope(value interface{}) *gorm.Scope {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewScope", value)
	ret0, _ := ret[0].(*gorm.Scope)
	return ret0
}

// NewScope indicates an expected call of NewScope
func (mr *MockDBIfaceMockRecorder) NewScope(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewScope", reflect.TypeOf((*MockDBIface)(nil).NewScope), value)
}

// Where mocks base method
func (m *MockDBIface) Where(query interface{}, args ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Where", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Where indicates an expected call of Where
func (mr *MockDBIfaceMockRecorder) Where(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Where", reflect.TypeOf((*MockDBIface)(nil).Where), varargs...)
}

// Or mocks base method
func (m *MockDBIface) Or(query interface{}, args ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Or", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Or indicates an expected call of Or
func (mr *MockDBIfaceMockRecorder) Or(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Or", reflect.TypeOf((*MockDBIface)(nil).Or), varargs...)
}

// Not mocks base method
func (m *MockDBIface) Not(query interface{}, args ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Not", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Not indicates an expected call of Not
func (mr *MockDBIfaceMockRecorder) Not(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Not", reflect.TypeOf((*MockDBIface)(nil).Not), varargs...)
}

// Limit mocks base method
func (m *MockDBIface) Limit(limit interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Limit", limit)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Limit indicates an expected call of Limit
func (mr *MockDBIfaceMockRecorder) Limit(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limit", reflect.TypeOf((*MockDBIface)(nil).Limit), limit)
}

// Offset mocks base method
func (m *MockDBIface) Offset(offset interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Offset", offset)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Offset indicates an expected call of Offset
func (mr *MockDBIfaceMockRecorder) Offset(offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Offset", reflect.TypeOf((*MockDBIface)(nil).Offset), offset)
}

// Order mocks base method
func (m *MockDBIface) Order(value interface{}, reorder ...bool) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{value}
	for _, a := range reorder {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Order", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Order indicates an expected call of Order
func (mr *MockDBIfaceMockRecorder) Order(value interface{}, reorder ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{value}, reorder...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Order", reflect.TypeOf((*MockDBIface)(nil).Order), varargs...)
}

// Select mocks base method
func (m *MockDBIface) Select(query interface{}, args ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Select", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Select indicates an expected call of Select
func (mr *MockDBIfaceMockRecorder) Select(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockDBIface)(nil).Select), varargs...)
}

// Omit mocks base method
func (m *MockDBIface) Omit(columns ...string) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range columns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Omit", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Omit indicates an expected call of Omit
func (mr *MockDBIfaceMockRecorder) Omit(columns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Omit", reflect.TypeOf((*MockDBIface)(nil).Omit), columns...)
}

// Group mocks base method
func (m *MockDBIface) Group(query string) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Group", query)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Group indicates an expected call of Group
func (mr *MockDBIfaceMockRecorder) Group(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Group", reflect.TypeOf((*MockDBIface)(nil).Group), query)
}

// Having mocks base method
func (m *MockDBIface) Having(query interface{}, values ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Having", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Having indicates an expected call of Having
func (mr *MockDBIfaceMockRecorder) Having(query interface{}, values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Having", reflect.TypeOf((*MockDBIface)(nil).Having), varargs...)
}

// Joins mocks base method
func (m *MockDBIface) Joins(query string, args ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Joins", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Joins indicates an expected call of Joins
func (mr *MockDBIfaceMockRecorder) Joins(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Joins", reflect.TypeOf((*MockDBIface)(nil).Joins), varargs...)
}

// Scopes mocks base method
func (m *MockDBIface) Scopes(funcs ...func(*gorm.DB) *gorm.DB) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range funcs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scopes", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Scopes indicates an expected call of Scopes
func (mr *MockDBIfaceMockRecorder) Scopes(funcs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scopes", reflect.TypeOf((*MockDBIface)(nil).Scopes), funcs...)
}

// Unscoped mocks base method
func (m *MockDBIface) Unscoped() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unscoped")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Unscoped indicates an expected call of Unscoped
func (mr *MockDBIfaceMockRecorder) Unscoped() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unscoped", reflect.TypeOf((*MockDBIface)(nil).Unscoped))
}

// Attrs mocks base method
func (m *MockDBIface) Attrs(attrs ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Attrs", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Attrs indicates an expected call of Attrs
func (mr *MockDBIfaceMockRecorder) Attrs(attrs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attrs", reflect.TypeOf((*MockDBIface)(nil).Attrs), attrs...)
}

// Assign mocks base method
func (m *MockDBIface) Assign(attrs ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Assign", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Assign indicates an expected call of Assign
func (mr *MockDBIfaceMockRecorder) Assign(attrs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockDBIface)(nil).Assign), attrs...)
}

// First mocks base method
func (m *MockDBIface) First(out interface{}, where ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{out}
	for _, a := range where {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "First", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// First indicates an expected call of First
func (mr *MockDBIfaceMockRecorder) First(out interface{}, where ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{out}, where...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockDBIface)(nil).First), varargs...)
}

// Take mocks base method
func (m *MockDBIface) Take(out interface{}, where ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{out}
	for _, a := range where {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Take", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Take indicates an expected call of Take
func (mr *MockDBIfaceMockRecorder) Take(out interface{}, where ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{out}, where...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockDBIface)(nil).Take), varargs...)
}

// Last mocks base method
func (m *MockDBIface) Last(out interface{}, where ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{out}
	for _, a := range where {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Last", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Last indicates an expected call of Last
func (mr *MockDBIfaceMockRecorder) Last(out interface{}, where ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{out}, where...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Last", reflect.TypeOf((*MockDBIface)(nil).Last), varargs...)
}

// Find mocks base method
func (m *MockDBIface) Find(out interface{}, where ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{out}
	for _, a := range where {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Find indicates an expected call of Find
func (mr *MockDBIfaceMockRecorder) Find(out interface{}, where ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{out}, where...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockDBIface)(nil).Find), varargs...)
}

// Preloads mocks base method
func (m *MockDBIface) Preloads(out interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preloads", out)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Preloads indicates an expected call of Preloads
func (mr *MockDBIfaceMockRecorder) Preloads(out interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preloads", reflect.TypeOf((*MockDBIface)(nil).Preloads), out)
}

// Scan mocks base method
func (m *MockDBIface) Scan(dest interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", dest)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Scan indicates an expected call of Scan
func (mr *MockDBIfaceMockRecorder) Scan(dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockDBIface)(nil).Scan), dest)
}

// Row mocks base method
func (m *MockDBIface) Row() *sql.Row {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Row")
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// Row indicates an expected call of Row
func (mr *MockDBIfaceMockRecorder) Row() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Row", reflect.TypeOf((*MockDBIface)(nil).Row))
}

// Rows mocks base method
func (m *MockDBIface) Rows() (*sql.Rows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rows")
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rows indicates an expected call of Rows
func (mr *MockDBIfaceMockRecorder) Rows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rows", reflect.TypeOf((*MockDBIface)(nil).Rows))
}

// ScanRows mocks base method
func (m *MockDBIface) ScanRows(rows *sql.Rows, result interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanRows", rows, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanRows indicates an expected call of ScanRows
func (mr *MockDBIfaceMockRecorder) ScanRows(rows, result interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanRows", reflect.TypeOf((*MockDBIface)(nil).ScanRows), rows, result)
}

// Pluck mocks base method
func (m *MockDBIface) Pluck(column string, value interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pluck", column, value)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Pluck indicates an expected call of Pluck
func (mr *MockDBIfaceMockRecorder) Pluck(column, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pluck", reflect.TypeOf((*MockDBIface)(nil).Pluck), column, value)
}

// Count mocks base method
func (m *MockDBIface) Count(value interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", value)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Count indicates an expected call of Count
func (mr *MockDBIfaceMockRecorder) Count(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockDBIface)(nil).Count), value)
}

// Related mocks base method
func (m *MockDBIface) Related(value interface{}, foreignKeys ...string) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{value}
	for _, a := range foreignKeys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Related", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Related indicates an expected call of Related
func (mr *MockDBIfaceMockRecorder) Related(value interface{}, foreignKeys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{value}, foreignKeys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Related", reflect.TypeOf((*MockDBIface)(nil).Related), varargs...)
}

// FirstOrInit mocks base method
func (m *MockDBIface) FirstOrInit(out interface{}, where ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{out}
	for _, a := range where {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FirstOrInit", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// FirstOrInit indicates an expected call of FirstOrInit
func (mr *MockDBIfaceMockRecorder) FirstOrInit(out interface{}, where ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{out}, where...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrInit", reflect.TypeOf((*MockDBIface)(nil).FirstOrInit), varargs...)
}

// FirstOrCreate mocks base method
func (m *MockDBIface) FirstOrCreate(out interface{}, where ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{out}
	for _, a := range where {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FirstOrCreate", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// FirstOrCreate indicates an expected call of FirstOrCreate
func (mr *MockDBIfaceMockRecorder) FirstOrCreate(out interface{}, where ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{out}, where...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreate", reflect.TypeOf((*MockDBIface)(nil).FirstOrCreate), varargs...)
}

// Update mocks base method
func (m *MockDBIface) Update(attrs ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockDBIfaceMockRecorder) Update(attrs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDBIface)(nil).Update), attrs...)
}

// Updates mocks base method
func (m *MockDBIface) Updates(values interface{}, ignoreProtectedAttrs ...bool) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{values}
	for _, a := range ignoreProtectedAttrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Updates", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Updates indicates an expected call of Updates
func (mr *MockDBIfaceMockRecorder) Updates(values interface{}, ignoreProtectedAttrs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{values}, ignoreProtectedAttrs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockDBIface)(nil).Updates), varargs...)
}

// UpdateColumn mocks base method
func (m *MockDBIface) UpdateColumn(attrs ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateColumn", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// UpdateColumn indicates an expected call of UpdateColumn
func (mr *MockDBIfaceMockRecorder) UpdateColumn(attrs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateColumn", reflect.TypeOf((*MockDBIface)(nil).UpdateColumn), attrs...)
}

// UpdateColumns mocks base method
func (m *MockDBIface) UpdateColumns(values interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateColumns", values)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// UpdateColumns indicates an expected call of UpdateColumns
func (mr *MockDBIfaceMockRecorder) UpdateColumns(values interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateColumns", reflect.TypeOf((*MockDBIface)(nil).UpdateColumns), values)
}

// Save mocks base method
func (m *MockDBIface) Save(value interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", value)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockDBIfaceMockRecorder) Save(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDBIface)(nil).Save), value)
}

// Create mocks base method
func (m *MockDBIface) Create(value interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", value)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockDBIfaceMockRecorder) Create(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDBIface)(nil).Create), value)
}

// Delete mocks base method
func (m *MockDBIface) Delete(value interface{}, where ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{value}
	for _, a := range where {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockDBIfaceMockRecorder) Delete(value interface{}, where ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{value}, where...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDBIface)(nil).Delete), varargs...)
}

// Raw mocks base method
func (m *MockDBIface) Raw(sql string, values ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{sql}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Raw", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Raw indicates an expected call of Raw
func (mr *MockDBIfaceMockRecorder) Raw(sql interface{}, values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{sql}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Raw", reflect.TypeOf((*MockDBIface)(nil).Raw), varargs...)
}

// Exec mocks base method
func (m *MockDBIface) Exec(sql string, values ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{sql}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Exec indicates an expected call of Exec
func (mr *MockDBIfaceMockRecorder) Exec(sql interface{}, values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{sql}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDBIface)(nil).Exec), varargs...)
}

// Model mocks base method
func (m *MockDBIface) Model(value interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Model", value)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Model indicates an expected call of Model
func (mr *MockDBIfaceMockRecorder) Model(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Model", reflect.TypeOf((*MockDBIface)(nil).Model), value)
}

// Table mocks base method
func (m *MockDBIface) Table(name string) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Table", name)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Table indicates an expected call of Table
func (mr *MockDBIfaceMockRecorder) Table(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Table", reflect.TypeOf((*MockDBIface)(nil).Table), name)
}

// Debug mocks base method
func (m *MockDBIface) Debug() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Debug")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Debug indicates an expected call of Debug
func (mr *MockDBIfaceMockRecorder) Debug() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockDBIface)(nil).Debug))
}

// Begin mocks base method
func (m *MockDBIface) Begin() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Begin indicates an expected call of Begin
func (mr *MockDBIfaceMockRecorder) Begin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDBIface)(nil).Begin))
}

// BeginTx mocks base method
func (m *MockDBIface) BeginTx(ctx context.Context, opts *sql.TxOptions) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, opts)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// BeginTx indicates an expected call of BeginTx
func (mr *MockDBIfaceMockRecorder) BeginTx(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockDBIface)(nil).BeginTx), ctx, opts)
}

// Commit mocks base method
func (m *MockDBIface) Commit() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Commit indicates an expected call of Commit
func (mr *MockDBIfaceMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockDBIface)(nil).Commit))
}

// Rollback mocks base method
func (m *MockDBIface) Rollback() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Rollback indicates an expected call of Rollback
func (mr *MockDBIfaceMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockDBIface)(nil).Rollback))
}

// RollbackUnlessCommitted mocks base method
func (m *MockDBIface) RollbackUnlessCommitted() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackUnlessCommitted")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// RollbackUnlessCommitted indicates an expected call of RollbackUnlessCommitted
func (mr *MockDBIfaceMockRecorder) RollbackUnlessCommitted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackUnlessCommitted", reflect.TypeOf((*MockDBIface)(nil).RollbackUnlessCommitted))
}

// NewRecord mocks base method
func (m *MockDBIface) NewRecord(value interface{}) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRecord", value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// NewRecord indicates an expected call of NewRecord
func (mr *MockDBIfaceMockRecorder) NewRecord(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRecord", reflect.TypeOf((*MockDBIface)(nil).NewRecord), value)
}

// RecordNotFound mocks base method
func (m *MockDBIface) RecordNotFound() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordNotFound")
	ret0, _ := ret[0].(bool)
	return ret0
}

// RecordNotFound indicates an expected call of RecordNotFound
func (mr *MockDBIfaceMockRecorder) RecordNotFound() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordNotFound", reflect.TypeOf((*MockDBIface)(nil).RecordNotFound))
}

// CreateTable mocks base method
func (m *MockDBIface) CreateTable(models ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range models {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTable", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// CreateTable indicates an expected call of CreateTable
func (mr *MockDBIfaceMockRecorder) CreateTable(models ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockDBIface)(nil).CreateTable), models...)
}

// DropTable mocks base method
func (m *MockDBIface) DropTable(values ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DropTable", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DropTable indicates an expected call of DropTable
func (mr *MockDBIfaceMockRecorder) DropTable(values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropTable", reflect.TypeOf((*MockDBIface)(nil).DropTable), values...)
}

// DropTableIfExists mocks base method
func (m *MockDBIface) DropTableIfExists(values ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DropTableIfExists", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DropTableIfExists indicates an expected call of DropTableIfExists
func (mr *MockDBIfaceMockRecorder) DropTableIfExists(values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropTableIfExists", reflect.TypeOf((*MockDBIface)(nil).DropTableIfExists), values...)
}

// HasTable mocks base method
func (m *MockDBIface) HasTable(value interface{}) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTable", value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasTable indicates an expected call of HasTable
func (mr *MockDBIfaceMockRecorder) HasTable(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTable", reflect.TypeOf((*MockDBIface)(nil).HasTable), value)
}

// AutoMigrate mocks base method
func (m *MockDBIface) AutoMigrate(values ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AutoMigrate", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// AutoMigrate indicates an expected call of AutoMigrate
func (mr *MockDBIfaceMockRecorder) AutoMigrate(values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoMigrate", reflect.TypeOf((*MockDBIface)(nil).AutoMigrate), values...)
}

// ModifyColumn mocks base method
func (m *MockDBIface) ModifyColumn(column, typ string) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyColumn", column, typ)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// ModifyColumn indicates an expected call of ModifyColumn
func (mr *MockDBIfaceMockRecorder) ModifyColumn(column, typ interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyColumn", reflect.TypeOf((*MockDBIface)(nil).ModifyColumn), column, typ)
}

// DropColumn mocks base method
func (m *MockDBIface) DropColumn(column string) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropColumn", column)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DropColumn indicates an expected call of DropColumn
func (mr *MockDBIfaceMockRecorder) DropColumn(column interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropColumn", reflect.TypeOf((*MockDBIface)(nil).DropColumn), column)
}

// AddIndex mocks base method
func (m *MockDBIface) AddIndex(indexName string, columns ...string) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{indexName}
	for _, a := range columns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddIndex", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// AddIndex indicates an expected call of AddIndex
func (mr *MockDBIfaceMockRecorder) AddIndex(indexName interface{}, columns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{indexName}, columns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIndex", reflect.TypeOf((*MockDBIface)(nil).AddIndex), varargs...)
}

// AddUniqueIndex mocks base method
func (m *MockDBIface) AddUniqueIndex(indexName string, columns ...string) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{indexName}
	for _, a := range columns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddUniqueIndex", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// AddUniqueIndex indicates an expected call of AddUniqueIndex
func (mr *MockDBIfaceMockRecorder) AddUniqueIndex(indexName interface{}, columns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{indexName}, columns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUniqueIndex", reflect.TypeOf((*MockDBIface)(nil).AddUniqueIndex), varargs...)
}

// RemoveIndex mocks base method
func (m *MockDBIface) RemoveIndex(indexName string) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveIndex", indexName)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// RemoveIndex indicates an expected call of RemoveIndex
func (mr *MockDBIfaceMockRecorder) RemoveIndex(indexName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveIndex", reflect.TypeOf((*MockDBIface)(nil).RemoveIndex), indexName)
}

// AddForeignKey mocks base method
func (m *MockDBIface) AddForeignKey(field, dest, onDelete, onUpdate string) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddForeignKey", field, dest, onDelete, onUpdate)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// AddForeignKey indicates an expected call of AddForeignKey
func (mr *MockDBIfaceMockRecorder) AddForeignKey(field, dest, onDelete, onUpdate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddForeignKey", reflect.TypeOf((*MockDBIface)(nil).AddForeignKey), field, dest, onDelete, onUpdate)
}

// RemoveForeignKey mocks base method
func (m *MockDBIface) RemoveForeignKey(field, dest string) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveForeignKey", field, dest)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// RemoveForeignKey indicates an expected call of RemoveForeignKey
func (mr *MockDBIfaceMockRecorder) RemoveForeignKey(field, dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveForeignKey", reflect.TypeOf((*MockDBIface)(nil).RemoveForeignKey), field, dest)
}

// Association mocks base method
func (m *MockDBIface) Association(column string) *gorm.Association {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Association", column)
	ret0, _ := ret[0].(*gorm.Association)
	return ret0
}

// Association indicates an expected call of Association
func (mr *MockDBIfaceMockRecorder) Association(column interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Association", reflect.TypeOf((*MockDBIface)(nil).Association), column)
}

// Preload mocks base method
func (m *MockDBIface) Preload(column string, conditions ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{column}
	for _, a := range conditions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Preload", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Preload indicates an expected call of Preload
func (mr *MockDBIfaceMockRecorder) Preload(column interface{}, conditions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{column}, conditions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preload", reflect.TypeOf((*MockDBIface)(nil).Preload), varargs...)
}

// Set mocks base method
func (m *MockDBIface) Set(name string, value interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", name, value)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockDBIfaceMockRecorder) Set(name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockDBIface)(nil).Set), name, value)
}

// InstantSet mocks base method
func (m *MockDBIface) InstantSet(name string, value interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstantSet", name, value)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// InstantSet indicates an expected call of InstantSet
func (mr *MockDBIfaceMockRecorder) InstantSet(name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstantSet", reflect.TypeOf((*MockDBIface)(nil).InstantSet), name, value)
}

// Get mocks base method
func (m *MockDBIface) Get(name string) (interface{}, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockDBIfaceMockRecorder) Get(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDBIface)(nil).Get), name)
}

// SetJoinTableHandler mocks base method
func (m *MockDBIface) SetJoinTableHandler(source interface{}, column string, handler gorm.JoinTableHandlerInterface) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetJoinTableHandler", source, column, handler)
}

// SetJoinTableHandler indicates an expected call of SetJoinTableHandler
func (mr *MockDBIfaceMockRecorder) SetJoinTableHandler(source, column, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJoinTableHandler", reflect.TypeOf((*MockDBIface)(nil).SetJoinTableHandler), source, column, handler)
}

// AddError mocks base method
func (m *MockDBIface) AddError(err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddError", err)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddError indicates an expected call of AddError
func (mr *MockDBIfaceMockRecorder) AddError(err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddError", reflect.TypeOf((*MockDBIface)(nil).AddError), err)
}

// GetErrors mocks base method
func (m *MockDBIface) GetErrors() []error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrors")
	ret0, _ := ret[0].([]error)
	return ret0
}

// GetErrors indicates an expected call of GetErrors
func (mr *MockDBIfaceMockRecorder) GetErrors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrors", reflect.TypeOf((*MockDBIface)(nil).GetErrors))
}
